name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  guvenlik-kontrolu:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kod Guvenlik Taramasi (Bandit)
        run: |
          pip install bandit
          bandit -r . || true 

      - name: Bagimlilik Taramasi (Safety)
        run: |
          pip install safety
          safety check -r requirements.txt || true

      - name: Docker Imajini Derle
        run: docker build -t benim-app:${{ github.sha }} .

      - name: Konteyner Taramasi (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'benim-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'